### ISSUE TITLE
Add kubectl config setup instructions for Windows

### ISSUE THREAD

**Issue by jimangel** [heptiolabs/gangway#132] opened 2019-05-28 14:34 UTC
Since Windows went GA in 1.14, it would be nice to leverage a simple OIDC `kubectl` context setup similar to the easy setup for linux (outputted in gangway).

Current issues are:
- stdout redirection creating the CA
- backslash escaping lines does not translate

We could have 2 info boxes (PowerShell and BASH or Windows and Mac / Linux). My preference would be to model around PowerShell vs. CMD. I'll help work on this if it doesn't get a ton of traction.

**Comment by alexbrand** [comment] 2019-05-28 14:41
Hey @jimangel, thanks for opening this issue. This is actually a duplicate of #102, so I am going to close this one. Please do add a comment on #102 with your thoughts. Thanks again!

**Closed by alexbrand** 2019-05-28 14:41 UTC
